music = {
    # Existing songs (already added)
    "believer": "https://www.youtube.com/watch?v=W0DM5lcj6mw",
    "somebody that i used to know": "https://www.youtube.com/watch?v=8UVNT4wvIGY",
    "enemy": "https://www.youtube.com/watch?v=hHB1Ikzfpmc",
    "faded": "https://www.youtube.com/watch?v=qdpXxGPqW-Y",
    "shape of you": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "see you again": "https://www.youtube.com/watch?v=RgKAFK5djSk",
    "cheap thrills": "https://www.youtube.com/watch?v=nYh-n7EOtMA",
    "let me down slowly": "https://www.youtube.com/watch?v=50VNCymT-Cs",
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "senorita": "https://www.youtube.com/watch?v=Pkh8UtuejGw",
    "girls like you": "https://www.youtube.com/watch?v=aJOTlE1K90k",
    "night changes": "https://www.youtube.com/watch?v=syFZfO_wfMQ",
    "stay": "https://www.youtube.com/watch?v=kTJczUoc26U",
    "on my way": "https://www.youtube.com/watch?v=dhYOPzcsbGM",
    "despacito": "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    "baby": "https://www.youtube.com/watch?v=kffacxfA7G4",
    "calm down": "https://www.youtube.com/watch?v=WcIcVapfqXw",
    "love me like you do": "https://www.youtube.com/watch?v=AJtDXIazrMo",
    "counting stars": "https://www.youtube.com/watch?v=hT_nvWreIhg",
    "sugar": "https://www.youtube.com/watch?v=09R8_2nJtjg",
    "levitating": "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
    "attention": "https://www.youtube.com/watch?v=nfs8NYg7yQM",
    "dusk till dawn": "https://www.youtube.com/watch?v=tt2k8PGm-TI",
    "unstoppable": "https://www.youtube.com/watch?v=c3LFNJqJJSk",
    "blank space": "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    "thinking out loud": "https://www.youtube.com/watch?v=lp-EO5I60KA",

    # More English hits
    "heat waves": "https://www.youtube.com/watch?v=mRD0-GxqHVo",
    "bones": "https://www.youtube.com/watch?v=TO-_3tck2tg",
    "thunder": "https://www.youtube.com/watch?v=fKopy74weus",
    "memories": "https://www.youtube.com/watch?v=SlPhMPnQ58k",
    "bad habits": "https://www.youtube.com/watch?v=orJSJGHjBLI",
    "anti hero": "https://www.youtube.com/watch?v=b1kbLwvqugk",
    "shivers": "https://www.youtube.com/watch?v=Il0S8BoucSA",
    "bad guy": "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    "roar": "https://www.youtube.com/watch?v=CevxZvSJLk8",
    "shake it off": "https://www.youtube.com/watch?v=nfWlot6h_JM",

    # Bollywood & Hindi Songs
    "apna bana le": "https://www.youtube.com/watch?v=Htaj3o3JD8I",
    "kesariya": "https://www.youtube.com/watch?v=BddP6PYo2gs",
    "tere vaaste": "https://www.youtube.com/watch?v=SeP3L5XrFOY",
    "maan meri jaan": "https://www.youtube.com/watch?v=p9Yx4F9Ubw4",
    "pasoori": "https://www.youtube.com/watch?v=5Eqb_-j3FDA",
    "tu aake dekh le": "https://www.youtube.com/watch?v=u4A8Qlxepb8",
    "tum se hi": "https://www.youtube.com/watch?v=8MRB7O5iRYs",
    "raataan lambiyan": "https://www.youtube.com/watch?v=gvyUuxdRdR4",
    "shayad": "https://www.youtube.com/watch?v=8ukxk6QKvvE",
    "kaise hua": "https://www.youtube.com/watch?v=JjZcJBTb6zU",
    "dil diyan gallan": "https://www.youtube.com/watch?v=SAcpESN_Fk4",

    # Motivational / Islamic Nasheeds
    "hasbi rabbi": "https://www.youtube.com/watch?v=fRA0s1h8VdY",
    "lab pe aati hai dua": "https://www.youtube.com/watch?v=8pgdKSXTL2g",
    "madine ko jaunga": "https://www.youtube.com/watch?v=YtoCuUxlqkE"
}
