sites = {
    "youtube": "https://www.youtube.com",
    "google": "https://www.google.com",
    "instagram": "https://www.instagram.com",
    "x": "https://x.com",
    "twitter": "https://x.com",
    "threads": "https://www.threads.net",
    "linkedin": "https://www.linkedin.com",
    "facebook": "https://www.facebook.com",
    "github": "https://github.com",
    "stackoverflow": "https://stackoverflow.com",
    "chatgpt": "https://chat.openai.com",
    "gmail": "https://mail.google.com",
    "reddit": "https://www.reddit.com",
    "pinterest": "https://www.pinterest.com",
    "netflix": "https://www.netflix.com",
    "amazon": "https://www.amazon.com",
    "flipkart": "https://www.flipkart.com",
    "udemy": "https://www.udemy.com",
    "coursera": "https://www.coursera.org",
    "khan academy": "https://www.khanacademy.org",
    "wikipedia": "https://www.wikipedia.org",
    "whatsapp web": "https://web.whatsapp.com",
    "spotify": "https://open.spotify.com",
    "canva": "https://www.canva.com",
    "zlibrary": "https://z-lib.io",
    "pixabay": "https://pixabay.com",
    "pexels": "https://www.pexels.com",
    "unsplash": "https://unsplash.com",
    "notion": "https://www.notion.so",
    "replit": "https://replit.com",
    "fiverr": "https://www.fiverr.com",
    "upwork": "https://www.upwork.com",
    "indeed": "https://www.indeed.com",
    "linkedin jobs": "https://www.linkedin.com/jobs",
    "leetcode": "https://leetcode.com",
    "geeksforgeeks": "https://www.geeksforgeeks.org",
    "programiz": "https://www.programiz.com",
    "hackerrank": "https://www.hackerrank.com",
    "youtube studio": "https://studio.youtube.com",
    "google drive": "https://drive.google.com",
    "google translate": "https://translate.google.com",
    "medium": "https://medium.com",
    "codepen": "https://codepen.io",
    "w3schools": "https://www.w3schools.com",
    "freecodecamp": "https://www.freecodecamp.org",
    "github gist": "https://gist.github.com",
    "jsfiddle": "https://jsfiddle.net",
    "discord": "https://discord.com",
    "telegram": "https://web.telegram.org",
    "quora": "https://www.quora.com",
    "duckduckgo": "https://duckduckgo.com",
    "cloudflare": "https://www.cloudflare.com",
    "wordpress": "https://wordpress.com",
    "envato": "https://envato.com",
    "behance": "https://www.behance.net",
    "dribbble": "https://dribbble.com",
    "freelancer": "https://www.freelancer.com",
    "airbnb": "https://www.airbnb.com",
    "booking": "https://www.booking.com",
    "courier": "https://www.courier.com",
    "figma": "https://www.figma.com",
    "vimeo": "https://vimeo.com",
    "twitch": "https://www.twitch.tv",
    "kick": "https://kick.com",
    "tiktok": "https://www.tiktok.com",
    "snapchat": "https://www.snapchat.com",
    "yahoo": "https://www.yahoo.com",
    "bing": "https://www.bing.com",
    "slideshare": "https://www.slideshare.net",
    "ted": "https://www.ted.com",
    "archive": "https://archive.org",
    "medium dev": "https://dev.to",
    "glitch": "https://glitch.com",
    "tradingview": "https://www.tradingview.com",
    "coinmarketcap": "https://coinmarketcap.com",
    "coingecko": "https://www.coingecko.com",
    "binance": "https://www.binance.com",
    "investopedia": "https://www.investopedia.com",
    "cnn": "https://edition.cnn.com",
    "bbc": "https://www.bbc.com",
    "aljazeera": "https://www.aljazeera.com",
    "nyt": "https://www.nytimes.com",
    "the guardian": "https://www.theguardian.com",
    "weather": "https://weather.com",
    "zoom": "https://zoom.us",
    "skype": "https://www.skype.com",
    "meet": "https://meet.google.com",
    "teams": "https://www.microsoft.com/en-us/microsoft-teams",
    "mailchimp": "https://mailchimp.com",
    "dropbox": "https://www.dropbox.com",
    "mega": "https://mega.nz",
    "protonmail": "https://proton.me",
    "icloud": "https://www.icloud.com",
    "bitbucket": "https://bitbucket.org",
    "kaggle": "https://www.kaggle.com",
    "figshare": "https://figshare.com",
    "shutterstock": "https://www.shutterstock.com",
    "gettyimages": "https://www.gettyimages.com",
    "bored panda": "https://www.boredpanda.com",
    "9gag": "https://9gag.com",
    "product hunt": "https://www.producthunt.com",
    "alternativeto": "https://alternativeto.net",
    "sitepoint": "https://www.sitepoint.com",
    "moz": "https://moz.com",
    "semrush": "https://www.semrush.com",
    "ahrefs": "https://ahrefs.com",
    "mail": "https://mail.com",
    "tumblr": "https://www.tumblr.com",
    "soundcloud": "https://soundcloud.com",
    "bandcamp": "https://bandcamp.com",
    "deezer": "https://www.deezer.com",
    "gaana": "https://gaana.com",
    "jiosaavn": "https://www.jiosaavn.com",
    "wynk": "https://wynk.in",
    "hotstar": "https://www.hotstar.com",
    "zee5": "https://www.zee5.com",
    "sonyliv": "https://www.sonyliv.com",
    "hoichoi": "https://www.hoichoi.tv",
    "mxplayer": "https://www.mxplayer.in",
    "crunchyroll": "https://www.crunchyroll.com",
    "kickstarter": "https://www.kickstarter.com",
    "indiegogo": "https://www.indiegogo.com",
    "deviantart": "https://www.deviantart.com",
    "trello": "https://trello.com",
    "asana": "https://asana.com",
    "slack": "https://slack.com",
    "loom": "https://www.loom.com",
    "notion calendar": "https://calendar.notion.so",
    "figma community": "https://www.figma.com/community",
    "productivity hub": "https://productivityhub.io"
}
